#!/bin/bash
echo "  ___               _  __ __   __  __  __      ___       "
echo " |   \   ___   ___ | |/ / \ \ / / |  \/  |    / __|  ___ "
echo " | |) | / -_) |_ / | ' <   \ V /  | |\/| |   | (_ | / _ \\"
echo " |___/  \___| /__| |_|\_\   \_/   |_|  |_|    \___| \___/"
echo "                                                         "
echo "                    -- IP KVM mode --                    "
echo ""
echo "Navigate to http://<this-machine>:8080 to open the KVM viewer"
echo ""
echo "Device nodes are detected automatically. To override them:"
echo "  go run . -video /dev/video0 -audio /dev/snd/pcmC3D0c -tty /dev/ttyUSB0"
echo "To see what can be detected:"
echo "  go run . -list-devices"
echo "-------------------------------------------"
go run . "$@"
